### ISSUE TITLE
API returns null when using DragonTreasureSetOwnerProcessor

### ISSUE THREAD

**Issue by nuryagdym** [SymfonyCasts/api-platform3#43]
Hi,
thanks for tutorials! I found an issue in [tutorial](https://symfonycasts.com/screencast/api-platform-security/auto-set-owner) code examples but don't know how to update tutorial in github.

in this example 
![image](https://github.com/SymfonyCasts/api-platform3/assets/26792980/c22d642f-e379-4e9b-b65c-96524eb31ce0)

the process() method needs to be updated to return 
```
return $this->innerProcessor->process($data, $operation, $uriVariables, $context);
```
 otherwise when I send a POST request I am receiving null response in the request body.

API Platform v3.2.7

**Comment by bocharsky-bw** [comment]
Hey! If I understand you correctly, you suggest replacing `$this->innerProcessor`  with `$this->persistProcessor`? That does not sound correct (though it might work for your specific case only). That's because as you can see in this code block https://symfonycasts.com/screencast/api-platform-security/auto-set-owner#codeblock-b66e1324b2 we inject the processor exactly as `$innerProcessor`, which means we should call that property. Did you name the property as `$persistProcessor` in your own code? Then it makes sense you should use that name in your own code, or change it to `$innerProcessor` to match the video. I hope that helps!

**Comment by nuryagdym** [comment]
@bocharsky-bw sorry about the confusion.
I updated the issue description, the name of property does not matter.
we just need to return the value of 
```
$this->innerProcessor->process($data, $operation, $uriVariables, $context);
```

**Comment by weaverryan** [comment]
This is legit - there was an unintentional change in API Platform 3.2... and though it seems counterintuitive, if you don't return the inner processor, now, nothing is returned from the processor system. 

I had already added a note about this to another chapter, and I've just added one to this as well - https://github.com/SymfonyCasts/api-platform3/commit/56957fe2acea35f3bda3c01db58a31a151801194

A corresponding note will be added to the video shortly.

Thanks @nuryagdym!
